# Created by trellis-cli v1.7.0
# Documentation: https://docs.roots.io/trellis/master/wordpress-sites/

wordpress_sites:
  jimpeterman.com:
    site_hosts:
    - canonical: jimpeterman.test
      redirects:
      - www.jimpeterman.test
    local_path: ../site
    admin_email: admin@jimpeterman.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
